---
- name: Send simple notification to MS Teams
  community.general.office_365_connector_card:
    webhook: "{{ msteams_url }}"
    summary: "{{ summary_text }}"
    sections:
    - title: "{{ card_title }}"
      activity_image: "{{ act_image }}"
      activity_title: "{{ act_title }}"
      activity_subtitle: "{{ act_subtitle }}"
      activity_text: "{{ act_text }}"
      facts: 
      - name: "{{ {{ item.name }} if {{ item.name }} is defined | default('') }}"
        value: "{{ {{ item.value }} if {{ item.value }} is defined | default('') }}"
  when: ms_teams_notification_type=="simple"
  loop: "{{ os_facts|dict2items }}"

- name: Send simple notification w/ one link to MS Teams
  community.general.office_365_connector_card:
    webhook: "{{ msteams_url }}"
    summary: "{{ summary_text }}"
    sections:
    - title: "{{ card_title }}"
      activity_image: "{{ act_image }}"
      activity_title: "{{ act_title }}"
      activity_subtitle: "{{ act_subtitle }}"
      activity_text: "{{ act_text }}"
    actions:
    - "@type": OpenUri
      name: "{{ link_name }}"
      targets:
      - os: default
        uri: "{{ link_url }}"
  when: ms_teams_notification_type=="simple_with_link"

- name: Send simple notification w/ one link to MS Teams
  community.general.office_365_connector_card:
    webhook: "{{ msteams_url }}"
    summary: "{{ summary_text }}"
    sections:
    - title: "{{ card_title }}"
      activity_image: "{{ act_image }}"
      activity_title: "{{ act_title }}"
      activity_subtitle: "{{ act_subtitle }}"
      activity_text: "{{ act_text }}"
    actions:
    - "@type": OpenUri
      name: "{{ link_name }}"
      targets:
      - os: default
        uri: "{{ link_url }}"
    - "@type": OpenUri
      name: "{{ sec_link_name }}"
      targets:
      - os: default
        uri: "{{ sec_link_url }}"
  when: ms_teams_notification_type=="simple_with_multiple_links"