- name: Create a simple Connector Card
  community.general.office_365_connector_card:
    webhook: "{{ msteams_url }}"
    summary: This is the summary property
    title: This is the **card's title** property
    text: "{{ card_text }}"
    color: E81123
    sections:
    - title: This is the **section's title** property
      activity_image: https://d2.alternativeto.net/dist/s/podman_510269_full.png?format=jpg&width=200&height=200&mode=crop
      activity_title: This is the section's **activityTitle** property
      activity_subtitle: This is the section's **activitySubtitle** property
      activity_text: This is the section's **activityText** property.
      hero_image:
        image: http://connectorsdemo.azurewebsites.net/images/WIN12_Scene_01.jpg
        title: This is the image's alternate text
      text: This is the section's text property. Lorem ipsum dolor sit amet, consectetur
        adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
