---
- name: Send notification to MS Teams
  community.general.office_365_connector_card:
    webhook: "{{ msteams_url }}"
    summary: "{{ summary_text }}"
    sections:
    - title: "{{ card_title }}"
      activity_image: "{{ act_image }}"
      activity_title: "{{ act_title }}"
      activity_subtitle: "{{ act_subtitle }}"
      activity_text: "{{ quotes | random }}"
      actions:
      - "@type": OpenUri
        name: "{{ link_name }}"
        targets:
        - os: default
          uri: "{{ link_url }}"
