---
- name: Send webhook-data to elasticsearch
  ansible.builtin.uri:
    url: "{{ elasticsearch_url }}/{{ indexname }}/_doc"
    method: POST
    return_content: yes
    body: |
      "time" : "{{ ansible_date_time.iso8601_micro }}"
    status_code: 201
  register: trigger
  changed_when: 201 == trigger.status
  ignore_errors: "{{ ignore_webhook_errors }}"